# Author: JAYENDRA VARDHAN SINGH
# SAP ID: 500082718
# ROLL NO: R214220566
# Batch: 5
# Course: Container Orchestration and Infrastructure Automation
# Program: BTECH CSE & Spl. CC&VT


# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /app

COPY . .

CMD [ "python", "client/client.py" ]